server.servlet.context-path: /

# To handle reverse proxy
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.webserver.use-behind-a-proxy-server.
# TODO: If custom headers are being used, then might change the strategy to FRAMEWORK
server.forward-headers-strategy: NATIVE

# Spring application name
spring.application.name: x-admin

springdoc:
  swagger-ui:
    path: ${spring.application.name}
    operationsSorter: method
    tagsSorter: alpha

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

xadmin.clinic:
    name: x-admin-app