spring.datasource:
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}

# DEPRECATED
# xadmin.jwt:
#  secret-key: ${XADMIN_JWT_SECRET_KEY}
#  expiration-time-in-ms: 18000000

xadmin.security:
  cors:
    allowed-hosts:
      - ${XADMIN_CORS_ALLOWED_HOST_1}