spring.config.import: vault://

spring.datasource:
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}

spring.cloud.vault:
  uri: ${SPRING_CLOUD_VAULT_URI}
  connection-timeout: ${SPRING_CLOUD_VAULT_CONNECTION_TIMEOUT:5000}
  read-timeout: ${SPRING_CLOUD_VAULT_READ_TIMEOUT:15000}
  
  # To authenticate to vault
  authentication: APP_ROLE
  fail-fast: true
  app-role:
    role-id: ${SPRING_CLOUD_VAULT_APP_ROLE_ROLE_ID}
    secret-id: ${SPRING_CLOUD_VAULT_APP_ROLE_SECRET_ID}

  # Enable vault's key-value
  kv:
    enable: true
    backend: secret

xadmin.security:
  cors:
    allowed-hosts:
      - ${XADMIN_CORS_ALLOWED_HOST_1}

xadmin.satusehat.integration:
  environment: ${SATU_SEHAT_PRODUCTION_ENVIRONMENT_NAME:production}
