# This flow pushes the image of the app to GitHub Packages
# 
# Reference: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Docker Image CI

# When this action will be triggered
on:
  pull_request:
    branches: [ "main" ]

# Defines environment variables for the workflow.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: acemitn/x-admin-backend:test

jobs:
# Set the workflow to run on ubuntu-latest
  build:
    runs-on: ubuntu-latest

# Give permissions to GITHUB_TOKEN
    permissions:
      contents: read
      packages: write

# Defines the steps use to from checkout till publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
